# File: nixpacks.toml

[phases.setup]
aptPkgs = ["pkg-config", "libmariadb-dev", "gcc"]

[phases.build]
# Override perintah build default agar tidak menjalankan migrate.
# Cukup install dependensi saja di sini.
cmds = ["pip install -r requirements.txt"]