# Generated by Django 5.0.1 on 2025-06-27 10:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogarticle",
            options={"verbose_name_plural": "2. Artikel Blog"},
        ),
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "1. Kategori"},
        ),
        migrations.AlterField(
            model_name="blogarticle",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Text"),
        ),
    ]
